config/routes.rb
Rails.application.routes.draw do
  # # 一覧画面へのルーティング
  # get '/users', to: 'users#index'
  # #新規投稿画面へのルーティング
  # get '/users/new', to: 'users#new'
  # #新規投稿を行うためのルーティング
  # post '/users', to: 'users#create'
  # #編集画面へのルーティング
  # get '/users/:id/edit', to: 'users#edit'
  # #更新を行うためのルーティング
  # patch '/users/:id',to: 'users#update'
  # #削除を行うためのルーティング
  # delete '/users/:id', to: 'users#destroy'
  # #詳細情報を表示するためのルーティング
  # get '/users/:id', to: 'users#show'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #一覧画面に対応するアクション
    def index
       @user = User.all 
    end
    
    #新規作成画面に対応するアクション
    def new
        @user = User.new
    end
    
    #新規登録を行うためのアクション 
    def create
        User.create(user_params)
        redirect_to action: :index
    end
    
    #詳細表示のアクション
    def show
        @user = User.find(params[:id])
    end

    #編集を行うためのアクション
    def edit
        @user = User.find(params[:id])
    end

    #更新を行うためのアクション
    def update
        user = User.find(params[:id])
        user.update(user_params)
        redirect_to action: :index
    end
    
    #削除を行うためのアクション
    def destroy
        user = User.find(params[:id])
        user.delete
        redirect_to action: :index
    end

    #ストロングパラメータ
    private
    def user_params
        params.require(:user).permit(:name,:age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudSample1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>登録完了</h1>
<%= link_to "一覧画面へ",user_path %>  

app/views/users/destroy.html.erb
<h1>削除完了</h1>
<%= link_to "一覧画面へ",user_path %>

app/views/users/edit.html.erb
<p>更新</p>
<%= form_with model:@user,url:user_path(@user.id),method: :patch,local: true do |f| %>
    <p><%= f.text_field :name %></p>
    <p><%= f.text_field :age %></p>
    <%= f.submit "送信" %>
<% end %>

app/views/users/index.html.erb
<%= link_to "投稿画面へ",new_user_path %>
<% @user.each do |user| %>
    <p>
        <%= user.name %>
        <%= user.age %>
        <%= link_to '詳細',user_path(user.id),method: :get %>
        <%= link_to '削除',user_path(user.id),method: :delete,data: {confirm: "削除しますか？"} %>
        <%= link_to '編集',edit_user_path(user.id),method: :get %>    
</p>
<% end %>

app/views/users/new.html.erb
<%= form_with model:@user,url: users_path,method: :post,local: true do |f| %>
    <p>投稿</p>
    <p>お名前:<%= f.text_field :name %></p>
    <p>年齢:<%= f.text_field :age %></p>
    <%= f.submit "送信" %>
<% end %>

app/views/users/show.html.erb
<h1>詳細情報</h1>
<p><%= @user.name %></p>
<p><%= @user.age %></p>

app/views/users/update.html.erb
<h1>更新完了</h1>
<%= link_to "一覧画面へ",user_path %>